-- Group Z
-- Z1905404,
-- CSCI466

-- insertion of artist name data
INSERT INTO Artist (Name) VALUES ("Lil Nas X");
INSERT INTO Artist (Name) VALUES ("Olivia Rodrigo");
INSERT INTO Artist (Name) VALUES ("Dua Lipa");
INSERT INTO Artist (Name) VALUES ("The Weeknd");
INSERT INTO Artist (Name) VALUES ("Masked Wolf");
INSERT INTO Artist (Name) VALUES ("Pop Smoke");
INSERT INTO Artist (Name) VALUES ("24kGoldn");
INSERT INTO Artist (Name) VALUES ("Drake");
INSERT INTO Artist (Name) VALUES ("The Kid LAROI");
INSERT INTO Artist (Name) VALUES ("Mooski");
INSERT INTO Artist (Name) VALUES ("Travis Scott");
INSERT INTO Artist (Name) VALUES ("CJ");
INSERT INTO Artist (Name) VALUES ("Roddy Ricch");
INSERT INTO Artist (Name) VALUES ("Doja Cat");
INSERT INTO Artist (Name) VALUES ("Kanye West");
INSERT INTO Artist (Name) VALUES ("Vance Joy");
INSERT INTO Artist (Name) VALUES ("Iyaz");
INSERT INTO Artist (Name) VALUES ("Logic");
INSERT INTO Artist (Name) VALUES ("Kid Cudi");
INSERT INTO Artist (Name) VALUES ("Juice WRLD");
INSERT INTO Artist (Name) VALUES ("J. Cole");
INSERT INTO Artist (Name) VALUES ("Childish Gambino");
INSERT INTO Artist (Name) VALUES ("LiSA");
INSERT INTO Artist (Name) VALUES ("TK");
INSERT INTO Artist (Name) VALUES ("Vickeblanka");
INSERT INTO Artist (Name) VALUES ("Linked Horizon");

-- insertion of user name data
INSERT INTO User (Name) VALUES ("Brady");
INSERT INTO User (Name) VALUES ("Joshua");
INSERT INTO User (Name) VALUES ("Samuel");
INSERT INTO User (Name) VALUES ("Jon");
INSERT INTO User (Name) VALUES ("Mary");
INSERT INTO User (Name) VALUES ("Jen");
INSERT INTO User (Name) VALUES ("Sarah");
INSERT INTO User (Name) VALUES ("Anna");
INSERT INTO User (Name) VALUES ("Nick");
INSERT INTO User (Name) VALUES ("Abigail");

-- insertion of contributer name data
INSERT INTO Contributor (Name) VALUES ("Montero Hill");
INSERT INTO Contributor (Name) VALUES ("Denzel Baptiste");
INSERT INTO Contributor (Name) VALUES ("David Biral");
INSERT INTO Contributor (Name) VALUES ("Omer Fedi");
INSERT INTO Contributor (Name) VALUES ("Rosario Lenzo");
INSERT INTO Contributor (Name) VALUES ("Take A Daytrip");
INSERT INTO Contributor (Name) VALUES ("Daniel Nigro");
INSERT INTO Contributor (Name) VALUES ("Olivia Rodrigo");
INSERT INTO Contributor (Name) VALUES ("DaBaby");
INSERT INTO Contributor (Name) VALUES ("Clarence Bernard Coffee");
INSERT INTO Contributor (Name) VALUES ("Sarah Theresa Hudson");
INSERT INTO Contributor (Name) VALUES ("Stephen Noel Kozmeniuk");
INSERT INTO Contributor (Name) VALUES ("Dua Lipa");
INSERT INTO Contributor (Name) VALUES ("KOZ");
INSERT INTO Contributor (Name) VALUES ("Stuart Price");
INSERT INTO Contributor (Name) VALUES ("Max Martin");
INSERT INTO Contributor (Name) VALUES ("Jason Quenneville");
INSERT INTO Contributor (Name) VALUES ("Oscar Holter");
INSERT INTO Contributor (Name) VALUES ("Ahmad Balshe");
INSERT INTO Contributor (Name) VALUES ("The Weeknd");
INSERT INTO Contributor (Name) VALUES ("Harry Michael");
INSERT INTO Contributor (Name) VALUES ("Tyron Hapi");
INSERT INTO Contributor (Name) VALUES ("Bashar Jackson");
INSERT INTO Contributor (Name) VALUES ("Elgin Lumpkin");
INSERT INTO Contributor (Name) VALUES ("Tashim Zene");
INSERT INTO Contributor (Name) VALUES ("Troy Oliver");
INSERT INTO Contributor (Name) VALUES ("IamTash");
INSERT INTO Contributor (Name) VALUES ("iann dior");
INSERT INTO Contributor (Name) VALUES ("Blake Slatkin");
INSERT INTO Contributor (Name) VALUES ("Golden Landis Von Jones");
INSERT INTO Contributor (Name) VALUES ("Keegan Bach");
INSERT INTO Contributor (Name) VALUES ("Michael Olmo");
INSERT INTO Contributor (Name) VALUES ("KBeaZy");
INSERT INTO Contributor (Name) VALUES ("Drake");
INSERT INTO Contributor (Name) VALUES ("Jonathan Demario Priester");
INSERT INTO Contributor (Name) VALUES ("Maneesh Bidaye");
INSERT INTO Contributor (Name) VALUES ("Supah Mario");
INSERT INTO Contributor (Name) VALUES ("Billy Walsh");
INSERT INTO Contributor (Name) VALUES ("Charlton Howard");
INSERT INTO Contributor (Name) VALUES ("Darien Hinton");
INSERT INTO Contributor (Name) VALUES ("Levi de Jong");
INSERT INTO Contributor (Name) VALUES ("Woodpecker");
INSERT INTO Contributor (Name) VALUES ("Kevin Gomringer");
INSERT INTO Contributor (Name) VALUES ("Tim Gomringer");
INSERT INTO Contributor (Name) VALUES ("Brock Korsan");
INSERT INTO Contributor (Name) VALUES ("Daveon Jackson");
INSERT INTO Contributor (Name) VALUES ("Jacques Webster");
INSERT INTO Contributor (Name) VALUES ("Kendrick Duckworth");
INSERT INTO Contributor (Name) VALUES ("Ronald LaTour");
INSERT INTO Contributor (Name) VALUES ("Cardo");
INSERT INTO Contributor (Name) VALUES ("CuBeatz");
INSERT INTO Contributor (Name) VALUES ("YeX");
INSERT INTO Contributor (Name) VALUES ("Charalambos Antoniou");
INSERT INTO Contributor (Name) VALUES ("Christopher Daniel Soriano");
INSERT INTO Contributor (Name) VALUES ("Mithoon");
INSERT INTO Contributor (Name) VALUES ("Pxcoyo");
INSERT INTO Contributor (Name) VALUES ("Samuel Gloade");
INSERT INTO Contributor (Name) VALUES ("Adarius Moragne");
INSERT INTO Contributor (Name) VALUES ("Aqeel Qadir Tate");
INSERT INTO Contributor (Name) VALUES ("Khirye Anthony Tyler");
INSERT INTO Contributor (Name) VALUES ("Larrance Dopson");
INSERT INTO Contributor (Name) VALUES ("Rodrick Moore");
INSERT INTO Contributor (Name) VALUES ("30 Roc");
INSERT INTO Contributor (Name) VALUES ("Datboisqueeze");
INSERT INTO Contributor (Name) VALUES ("Amala Zandile Dlamini");
INSERT INTO Contributor (Name) VALUES ("Lukasz Gottwald");
INSERT INTO Contributor (Name) VALUES ("Lydia Asrat");
INSERT INTO Contributor (Name) VALUES ("TYSON  TRAX");
INSERT INTO Contributor (Name) VALUES ("Jeff Bhasker");
INSERT INTO Contributor (Name) VALUES ("Mr Hudson");
INSERT INTO Contributor (Name) VALUES ("Kanye West");
INSERT INTO Contributor (Name) VALUES ("Malik Yusef Jones");
INSERT INTO Contributor (Name) VALUES ("No I.D");
INSERT INTO Contributor (Name) VALUES ("Scott Mescudi");
INSERT INTO Contributor (Name) VALUES ("Vancy Joy");
INSERT INTO Contributor (Name) VALUES ("Edwin White");
INSERT INTO Contributor (Name) VALUES ("James Keogh");
INSERT INTO Contributor (Name) VALUES ("John Castle");
INSERT INTO Contributor (Name) VALUES ("Jason Desrouleaux");
INSERT INTO Contributor (Name) VALUES ("Jonathan Rotem");
INSERT INTO Contributor (Name) VALUES ("K. Smith");
INSERT INTO Contributor (Name) VALUES ("Keidran Jones");
INSERT INTO Contributor (Name) VALUES ("Kisean Anderson");
INSERT INTO Contributor (Name) VALUES ("Theron Thomas");
INSERT INTO Contributor (Name) VALUES ("Timothy Thomas");
INSERT INTO Contributor (Name) VALUES ("Arkae Tuazon");
INSERT INTO Contributor (Name) VALUES ("Chazwick Bundick");
INSERT INTO Contributor (Name) VALUES ("Dexter Wansel");
INSERT INTO Contributor (Name) VALUES ("Garry Marshall Shider");
INSERT INTO Contributor (Name) VALUES ("George Bernard Worrell Jr");
INSERT INTO Contributor (Name) VALUES ("George Clinton Jr");
INSERT INTO Contributor (Name) VALUES ("Sir Robert Bryson Hall II");
INSERT INTO Contributor (Name) VALUES ("Kajo");
INSERT INTO Contributor (Name) VALUES ("Logic");
INSERT INTO Contributor (Name) VALUES ("Toro y Moi");
INSERT INTO Contributor (Name) VALUES ("Emile Haynie");
INSERT INTO Contributor (Name) VALUES ("Jarad Higgins");
INSERT INTO Contributor (Name) VALUES ("Nick Mira");
INSERT INTO Contributor (Name) VALUES ("Brandt Jones");
INSERT INTO Contributor (Name) VALUES ("Danell Stevens");
INSERT INTO Contributor (Name) VALUES ("Darius Barnes");
INSERT INTO Contributor (Name) VALUES ("Earl Stevens");
INSERT INTO Contributor (Name) VALUES ("J. Cole");
INSERT INTO Contributor (Name) VALUES ("Jordan Houston");
INSERT INTO Contributor (Name) VALUES ("Marvin Whitemon");
INSERT INTO Contributor (Name) VALUES ("Paul Beauregard");
INSERT INTO Contributor (Name) VALUES ("Tenina Stevens");
INSERT INTO Contributor (Name) VALUES ("Arjun Ivatury");
INSERT INTO Contributor (Name) VALUES ("Narada Michael Walden");
INSERT INTO Contributor (Name) VALUES ("Ludwig Goransson");
INSERT INTO Contributor (Name) VALUES ("Donald Glover");
INSERT INTO Contributor (Name) VALUES ("Brion Unger");
INSERT INTO Contributor (Name) VALUES ("Manzel Bush");
INSERT INTO Contributor (Name) VALUES ("Mark Farner");
INSERT INTO Contributor (Name) VALUES ("Vinylz");
INSERT INTO Contributor (Name) VALUES ("Anthony Parrino");
INSERT INTO Contributor (Name) VALUES ("Ronnie Foster");
INSERT INTO Contributor (Name) VALUES ("Abrim Tilmon");
INSERT INTO Contributor (Name) VALUES ("André Romell Young");
INSERT INTO Contributor (Name) VALUES ("Bernie Worrell");
INSERT INTO Contributor (Name) VALUES ("Claire Courchene");
INSERT INTO Contributor (Name) VALUES ("Eric Wright");
INSERT INTO Contributor (Name) VALUES ("George Clinton");
INSERT INTO Contributor (Name) VALUES ("Guy Wood");
INSERT INTO Contributor (Name) VALUES ("Kevin Randolph");
INSERT INTO Contributor (Name) VALUES ("Lorenzo Patterson");
INSERT INTO Contributor (Name) VALUES ("Rob Kinelski");
INSERT INTO Contributor (Name) VALUES ("Robert Bryson Hall");
INSERT INTO Contributor (Name) VALUES ("Robert Mellin");
INSERT INTO Contributor (Name) VALUES ("Steve Wyreman");
INSERT INTO Contributor (Name) VALUES ("William Collins");
INSERT INTO Contributor (Name) VALUES ("Sho Watanbe");
INSERT INTO Contributor (Name) VALUES ("Toru Kitajima");
INSERT INTO Contributor (Name) VALUES ("Vickeblanka");
INSERT INTO Contributor (Name) VALUES ("REVO");

-- insertion of title name data
INSERT INTO Title (Name) VALUES ("Montero (Call Me By Your Name)");
INSERT INTO Title (Name) VALUES ("Drivers License");
INSERT INTO Title (Name) VALUES ("Levitating");
INSERT INTO Title (Name) VALUES ("Blinding Lights");
INSERT INTO Title (Name) VALUES ("Astronaut in the Ocean");
INSERT INTO Title (Name) VALUES ("What You Know Bout Love");
INSERT INTO Title (Name) VALUES ("Mood");
INSERT INTO Title (Name) VALUES ("What's Next");
INSERT INTO Title (Name) VALUES ("Without You");
INSERT INTO Title (Name) VALUES ("Track Star");
INSERT INTO Title (Name) VALUES ("Goosebumps");
INSERT INTO Title (Name) VALUES ("Whoopty");
INSERT INTO Title (Name) VALUES ("The Box");
INSERT INTO Title (Name) VALUES ("Say So");
INSERT INTO Title (Name) VALUES ("Heartless");
INSERT INTO Title (Name) VALUES ("Riptide");
INSERT INTO Title (Name) VALUES ("Replay");
INSERT INTO Title (Name) VALUES ("Dark Place");
INSERT INTO Title (Name) VALUES ("Soundtrack 2 My Life");
INSERT INTO Title (Name) VALUES ("All Girls Are The Same");
INSERT INTO Title (Name) VALUES ("No Role Modelz");
INSERT INTO Title (Name) VALUES ("Nikki");
INSERT INTO Title (Name) VALUES ("3005");
INSERT INTO Title (Name) VALUES ("Fire Squad");
INSERT INTO Title (Name) VALUES ("Neighbors");
INSERT INTO Title (Name) VALUES ("Under Pressure");
INSERT INTO Title (Name) VALUES ("Crossing Field");
INSERT INTO Title (Name) VALUES ("Unravel");
INSERT INTO Title (Name) VALUES ("Black Rover");
INSERT INTO Title (Name) VALUES ("Shinzou wo Sasageyo");

-- insertion of karaoke file data
INSERT INTO KaraokeFile (ArtistID, TitleID, Version) VALUES (1,1,1);
INSERT INTO KaraokeFile (ArtistID, TitleID, Version) VALUES (1,1,2);
INSERT INTO KaraokeFile (ArtistID, TitleID, Version) VALUES (2,2,1);
INSERT INTO KaraokeFile (ArtistID, TitleID, Version) VALUES (3,3,1);
INSERT INTO KaraokeFile (ArtistID, TitleID, Version) VALUES (4,4,1);
INSERT INTO KaraokeFile (ArtistID, TitleID, Version) VALUES (4,4,2);
INSERT INTO KaraokeFile (ArtistID, TitleID, Version) VALUES (5,5,1);
INSERT INTO KaraokeFile (ArtistID, TitleID, Version) VALUES (6,6,1);
INSERT INTO KaraokeFile (ArtistID, TitleID, Version) VALUES (6,6,2);
INSERT INTO KaraokeFile (ArtistID, TitleID, Version) VALUES (7,7,1);
INSERT INTO KaraokeFile (ArtistID, TitleID, Version) VALUES (8,8,1);
INSERT INTO KaraokeFile (ArtistID, TitleID, Version) VALUES (9,9,1);
INSERT INTO KaraokeFile (ArtistID, TitleID, Version) VALUES (10,10,1);
INSERT INTO KaraokeFile (ArtistID, TitleID, Version) VALUES (10,10,2);
INSERT INTO KaraokeFile (ArtistID, TitleID, Version) VALUES (11,11,1);
INSERT INTO KaraokeFile (ArtistID, TitleID, Version) VALUES (12,12,1);
INSERT INTO KaraokeFile (ArtistID, TitleID, Version) VALUES (13,13,1);
INSERT INTO KaraokeFile (ArtistID, TitleID, Version) VALUES (14,14,1);
INSERT INTO KaraokeFile (ArtistID, TitleID, Version) VALUES (15,15,1);
INSERT INTO KaraokeFile (ArtistID, TitleID, Version) VALUES (16,16,1);
INSERT INTO KaraokeFile (ArtistID, TitleID, Version) VALUES (17,17,1);
INSERT INTO KaraokeFile (ArtistID, TitleID, Version) VALUES (17,17,2);
INSERT INTO KaraokeFile (ArtistID, TitleID, Version) VALUES (18,18,1);
INSERT INTO KaraokeFile (ArtistID, TitleID, Version) VALUES (19,19,1);
INSERT INTO KaraokeFile (ArtistID, TitleID, Version) VALUES (20,20,1);
INSERT INTO KaraokeFile (ArtistID, TitleID, Version) VALUES (21,21,1);
INSERT INTO KaraokeFile (ArtistID, TitleID, Version) VALUES (18,22,1);
INSERT INTO KaraokeFile (ArtistID, TitleID, Version) VALUES (22,23,1);
INSERT INTO KaraokeFile (ArtistID, TitleID, Version) VALUES (21,24,1);
INSERT INTO KaraokeFile (ArtistID, TitleID, Version) VALUES (21,25,1);
INSERT INTO KaraokeFile (ArtistID, TitleID, Version) VALUES (18,26,1);
INSERT INTO KaraokeFile (ArtistID, TitleID, Version) VALUES (23,27,1);
INSERT INTO KaraokeFile (ArtistID, TitleID, Version) VALUES (24,28,1);
INSERT INTO KaraokeFile (ArtistID, TitleID, Version) VALUES (25,29,1);
INSERT INTO KaraokeFile (ArtistID, TitleID, Version) VALUES (26,30,1);
INSERT INTO KaraokeFile (ArtistID, TitleID, Version) VALUES (26,30,2);


--insertion of contributes data
INSERT INTO Contributes (FileID, ConID, Position) VALUES (1,1, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (1,2, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (1,3, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (1,4, "Writer and Producer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (1,5, "Writer and Producer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (1,6, "Producer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (2,1, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (2,2, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (2,3, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (2,4, "Writer and Producer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (2,5, "Writer and Producer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (2,6, "Producer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (3,7, "Writer and Producer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (3,8, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (4,9, "Vocals");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (4,10, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (4,11, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (4,12, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (4,13, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (4,14, "Producer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (4,15, "Producer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (5,16, "Writer and Producer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (5,20, "Writer and Producer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (5,17, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (5,18, "Writer and Producer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (5,19, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (6,16, "Writer and Producer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (6,20, "Writer and Producer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (6,17, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (6,18, "Writer and Producer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (6,19, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (7,21, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (7,22, "Writer and Producer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (8,23, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (8,24, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (8,25, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (8,26, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (8,27, "Producer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (9,23, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (9,24, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (9,25, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (9,26, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (9,27, "Producer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (10,28, "Vocals");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (10,29, "Writer and Producer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (10,4, "Writer and Producer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (10,30, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (10,31, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (10,32, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (10,33, "Producer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (11,34, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (11,35, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (11,36, "Writer and Producer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (11,37, "Producer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (12,38, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (12,29, "Writer and Producer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (12,4, "Writer and Producer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (12,39, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (13,40, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (13,41, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (13,42, "Producer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (14,40, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (14,41, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (14,42, "Producer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (15,43, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (15,44, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (15,45, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (15,46, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (15,47, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (15,48, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (15,49, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (15,50, "Producer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (15,51, "Producer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (15,52, "Producer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (16,53, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (16,54, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (16,55, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (16,56, "Producer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (17,57, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (17,58, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (17,59, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (17,60, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (17,61, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (17,62, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (17,63, "Producer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (17,64, "Producer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (18,65, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (18,66, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (18,67, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (18,68, "Producer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (19,69, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (19,70, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (19,71, "Writer and Producer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (19,72, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (19,73, "Writer and Producer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (19,74, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (20,75, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (20,76, "Producer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (20,77, "Producer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (20,78, "Producer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (21,79, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (21,80, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (21,81, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (21,82, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (21,83, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (21,84, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (21,85, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (22,79, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (22,80, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (22,81, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (22,82, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (22,83, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (22,84, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (22,85, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (23,86, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (23,87, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (23,88, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (23,89, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (23,90, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (23,91, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (23,92, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (23,93, "Producer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (23,94, "Producer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (23,95, "Producer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (24,74, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (24,96, "Producer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (25,97, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (25,98, "Writer and Producer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (26,99, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (26,100, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (26,101, "Writer and Producer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (26,102, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (26,103, "Writer and Producer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (26,104, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (26,105, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (26,106, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (26,107, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (27,108, "Writer and Producer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (27,109, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (27,92, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (27,94, "Producer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (28,110, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (28,111, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (29,112, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (29,103, "Writer and Producer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (29,113, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (29,114, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (29,115, "Producer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (30,116, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (30,103, "Writer and Producer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (30,117, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (31,118, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (31,119, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (31,120, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (31,121, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (31,122, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (31,123, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (31,124, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (31,125, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (31,126, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (31,127, "Writer and Producer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (31,128, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (31,129, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (31,130, "Writer and Producer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (31,131, "Writer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (31,94, "Producer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (32,132, "Writer and Producer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (33,133, "Writer and Producer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (34,134, "Writer and Producer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (35,135, "Writer and Producer");
INSERT INTO Contributes (FileID, ConID, Position) VALUES (36,135, "Writer and Producer");

-- insertion of users and data into free queue
INSERT INTO FQ (UserID, FileID, Time, Playing) VALUES (10, 1, "20:30:00", FALSE);
INSERT INTO FQ (UserID, FileID, Time, Playing) VALUES (9, 22, "20:34:00", FALSE);
INSERT INTO FQ (UserID, FileID, Time, Playing) VALUES (8, 15, "20:38:00", FALSE);
INSERT INTO FQ (UserID, FileID, Time, Playing) VALUES (7, 6, "20:42:00", FALSE);
INSERT INTO FQ (UserID, FileID, Time, Playing) VALUES (6, 9, "20:46:00", FALSE);

-- insertion of users and data into paid queue
INSERT INTO PQ (UserID, FileID, Time, Playing, Price) VALUES (5, 19, "20:50:00", FALSE, 10.00);
INSERT INTO PQ (UserID, FileID, Time, Playing, Price) VALUES (4, 4, "20:50:00", FALSE, 11.00);
INSERT INTO PQ (UserID, FileID, Time, Playing, Price) VALUES (3, 26, "20:50:00", FALSE, 12.00);
INSERT INTO PQ (UserID, FileID, Time, Playing, Price) VALUES (2, 12, "20:50:00", FALSE, 13.00);
INSERT INTO PQ (UserID, FileID, Time, Playing, Price) VALUES (1, 32, "20:50:00", FALSE, 14.00);
